apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: retort-app-com-tls
spec:
  secretName: retort-app-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: retort-app.com
  dnsNames:
    - retort-app.com
    - www.retort-app.com