    name: Deploy multi-k8s
    on:
      push:
        branches:
          - master
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - id: 'auth'
            name: 'Authenticate to Google Cloud'
            uses: 'google-github-actions/auth@v0'
            with:
              credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          - run: curl https://sdk.cloud.google.com | bash > /dev/null
          - run: source $HOME/google-cloud-sdk/path.bash.inc
          - run: sudo apt update
          - run: sudo apt install kubectl
          # - run: gcloud auth activate-service-account --key-file service-account.json
          # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          # - run: docker build -t phantomskiers/react-test -f ./client/Dockerfile.dev ./client
          # - run: docker run -e CI=true phantomskiers/react-test npm test -- --coverage
          # - run: docker build -t phantomskiers/multi-client ./client
          # - run: docker build -t phantomskiers/multi-nginx ./nginx
          # - run: docker build -t phantomskiers/multi-server ./server
          # - run: docker build -t phantomskiers/multi-worker ./worker
          # - run: docker push phantomskiers/multi-client
          # - run: docker push phantomskiers/multi-nginx
          # - run: docker push phantomskiers/multi-server
          # - run: docker push phantomskiers/multi-worker

          # - name: Generate deployment package
          #   run: zip -r deploy.zip . -x '*.git*'
     
          # - name: Deploy to EB
          #   uses: einaregilsson/beanstalk-deploy@v18
          #   with:
          #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          #     application_name: multi-docker2
          #     environment_name: Multidocker2-env
          #     existing_bucket_name: elasticbeanstalk-us-east-1-868900174760
          #     region: us-east-1
          #     version_label: ${{ github.sha }}
          #     wait_for_environment_recovery: 120
          #     deployment_package: deploy.zip